import { useMutation, useQuery } from 'convex/react';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - generated by Convex after `npx convex dev`
import { api } from '../../convex/_generated/api';

export const useHighlights = (documentId?: string) => {
  const highlights = useQuery(api.highlights.list, documentId ? { documentId } : { documentId: undefined });
  const summary = useQuery(api.highlights.summary, documentId ? { documentId } : 'skip');
  const createHighlight = useMutation(api.highlights.create);
  const deleteHighlight = useMutation(api.highlights.remove);

  return {
    highlights,
    summary,
    createHighlight,
    deleteHighlight,
  };
};
